### ISSUE TITLE
已签到没有加土币

### ISSUE THREAD

**Issue by wlcp** [bcvgh/t00ls_sign#1]
页面显示已签到，py脚本执行通知内容也是success，但是没有加TuBi，老哥知道啥情况吗

**Comment by bcvgh** [comment]
你是不是第一次签到，好像是连续两天以上签到才有tubi吧


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bcvgh/t00ls_sign"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 中午11:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[bcvgh/t00ls_sign] 已签到没有加土币 (Issue #1)





 
页面显示已签到，py脚本执行通知内容也是success，但是没有加TuBi，老哥知道啥情况吗
